### ISSUE TITLE
Support for NGINX error log "timestamp"

### ISSUE THREAD

**Issue by za267** [linux-wizard/timegrep#4]
Hello,

I use timegrep.py to seek through logs of the latest full minute, for use with Zabbix.  Some of the files I scan through are in the 2Gb size range, and although this tool is EXCELLENT, I found that it doesn't support the strange timestamp NGINX uses for its error logs.  Unfortunately, it is hardcoded in the nginx source, so it is not flexible:

YYYY/MM/DD HH:MM:SS

Would you be able to add this format to the logformat_list array?

logformat_list.append({'regexp':"(?P<YEAR>[0-9]{4})/(?P<MONTH>[0-9]{2})/(?P<DAY>[0-9]{2}) (?P<HOURS>[0-9]{2}):(?P<MINUTES>[0-9]{2}):(?P<SECONDS>[0-9]{2})", 'name':"NGINX Error", 'description':"%Y/%b/%d %H:%M:%S"})

Thank you for your consideration!

**Comment by za267** [comment]
Thank you for your consideration!

**Comment by linux-wizard** [comment]
Thanks for your report :)

**Comment by za267** [comment]
Thank you for implementing it.  I didn't know how to push a patch… 





From: Fabrice FACORAT
Sent: ‎Tuesday‎, ‎April‎ ‎07‎, ‎2015 ‎7‎:‎15‎ ‎PM
To: linux-wizard/timegrep
Cc: Xavier Lashmar





Thanks for your report :)
